---
name: Build & Push
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Calculate Commit Hash
      id: commit
      uses: pr-mpt/actions-commit-hash@v1

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

    - name: Build Docker Image
      run: docker build -t $GITHUB_REPOSITORY:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        TAG: ${{ steps.commit.outputs.short }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
      run: |-
        docker tag $GITHUB_REPOSITORY:latest us-central1-docker.pkg.dev/$PROJECT_ID/kutaisi-poc/$GITHUB_REPOSITORY:latest
        docker tag $GITHUB_REPOSITORY:latest us-central1-docker.pkg.dev/$PROJECT_ID/kutaisi-poc/$GITHUB_REPOSITORY:$TAG
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/kutaisi-poc/$GITHUB_REPOSITORY:latest
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/kutaisi-poc/$GITHUB_REPOSITORY:$TAG

    - name: Deploy to Cloud Run
      id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: 'kutaisi-poc'
        image: us-central1-docker.pkg.dev/$PROJECT_ID/kutaisi-poc/$GITHUB_REPOSITORY:latest