---
name: Build & Push
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: kutaisi-poc
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Calculate Commit Hash
      id: commit
      uses: pr-mpt/actions-commit-hash@v1

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

    - name: Build Docker Image
      run: docker build -t $PROJECT_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        TAG: ${{ steps.commit.outputs.short }}
      run: |-
        docker tag ${{ env.PROJECT_NAME }}:latest us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/kutaisi-poc/${{ env.PROJECT_NAME }}:latest
        docker tag ${{ env.PROJECT_NAME }}:latest us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/kutaisi-poc/${{ env.PROJECT_NAME }}:${{ env.TAG }}
        docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/kutaisi-poc/${{ env.PROJECT_NAME }}:latest
        docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/kutaisi-poc/${{ env.PROJECT_NAME }}:${{ env.TAG }}

    - name: Deploy to Cloud Run
      id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        metadata: |-
          apiVersion: serving.knative.dev/v1
          kind: Service
          metadata:
            name: ${{ env.PROJECT_NAME }}
            annotations:
              run.googleapis.com/ingress: all
              run.googleapis.com/ingress-status: all
          spec:
            template:
              metadata:
                annotations:
                  autoscaling.knative.dev/maxScale: '1'
                  autoscaling.knative.dev/minScale: '1'
              spec:
                containers:
                - image: us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/kutaisi-poc/${{ env.PROJECT_NAME }}:latest
                  ports:
                  - containerPort: 8080
                    name: http1
                  resources:
                    limits:
                      cpu: 1000m
                      memory: 512Mi

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'